### ISSUE TITLE
Error when building ICO_Template

### ISSUE THREAD

**Issue by Chubby-Chocobo** [neo-project/examples-csharp#11]
To whom it may concern,
I checked out repos at the latest commit `3544cc42d4c9c8f868ce22dca51f83af0fccf744`
When building ICO_Template project this error occurs:
```
1>------ Rebuild All started: Project: ICO_Template, Configuration: Debug Any CPU ------
1>  ICO_Template -> C:\workspace\examples-csharp\ICO_Template\bin\Debug\ICO_Template.dll
1>  Start NeoContract converter, Source File: C:\workspace\examples-csharp\ICO_Template\bin\Debug\ICO_Template.dll
1>  Neo.Compiler.MSIL console app v2.0.3.0
1>CONVERTTASK : LoadModule error : System.Exception: can't parese event type from:System.Action`3<System.Byte[],System.Byte[],System.Numerics.BigInteger>.maybe it is System.Action<xxx> which is defined in mscorlib.dll，copy this dll in.
1>     at Neo.Compiler.MSIL.ILField..ctor(ILType type, FieldDefinition field)
1>     at Neo.Compiler.MSIL.ILType..ctor(ILModule module, TypeDefinition type)
1>     at Neo.Compiler.MSIL.ILModule.LoadModule(Stream dllStream, Stream pdbStream)
1>     at Neo.Compiler.Program.Main(String[] args)
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

My system specs:
```
Windows 10 Education
MS Visual Studio Professional 2017 - Version 15.4.5
MS .NET Framework Version 4.7.02053
```
Could you please take a look into this issue?

One more thing, I'm new in NEO world and looking for a tutorial/example to implement an ICO, like https://aphelion.org/
Is there any more detailed example/tutorial for newbie to understand and follow?

Many thanks,

**Comment by erikzhang** [comment]
Try the latest version of compiler: https://github.com/neo-project/neo-compiler

**Comment by Chubby-Chocobo** [comment]
I've tried the latest version of compiler, but the error still occurs.

**Comment by erikzhang** [comment]
@lightszero Can you check this?

**Comment by lightszero** [comment]
you need to find a mscorlib.dll from
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework
and copy it to where Neo.SmartContract.Framework.dll and .avm is.

**Comment by tanZiWen** [comment]
![623dd85263998b768e8cec7fa0d5aca7](https://user-images.githubusercontent.com/8327633/34345099-3605975a-ea27-11e7-9f6e-05e1e5d0ff0b.png)

Try copy mscorlib.dll to you directory C:\workspace\examples-csharp\ICO_Template\bin\Debug\

**Comment by facadev** [comment]
Any instruction for Mac users given the full-fledged .NET Framework doesn't support macOS? @tanZiWen tan

**Comment by apisit** [comment]
I'm also on mac. 
got this error when I am trying to compile `ICO_Template.dll`

```
LoadModule Error:System.Exception: can't parese event type from:System.Action`3<System.Byte[],System.Byte[],System.Numerics.BigInteger>.maybe it is System.Action<xxx> which is defined in mscorlib.dll，copy this dll in.
   at Neo.Compiler.MSIL.ILField..ctor(ILType type, FieldDefinition field) in /Users/xxxx/xxxx/neo-compiler-master/neon/MSIL/ILModule.cs:line 127
   at Neo.Compiler.MSIL.ILType..ctor(ILModule module, TypeDefinition type) in /Users/xxxx/xxxx/neo-compiler-master/neon/MSIL/ILModule.cs:line 73
   at Neo.Compiler.MSIL.ILModule.LoadModule(Stream dllStream, Stream pdbStream) in /Users/apisit/Downloads/neo-compiler-master/neon/MSIL/ILModule.cs:line 48
   at Neo.Compiler.Program.Main(String[] args) in /Users/xxxx/xxxx/neo-compiler-master/neon/Program.cs:line 71
```
I tried copying `mscorlib.dll` into where `ICO_Template.dll ` is located but doesn't seem to help.

I was able to compile the simple HelloWorld just fine.

**Comment by apisit** [comment]
so I finally have this solved.
so this is the updated code for ICO_Template.cs

```csharp
public delegate void MyAction<T, T1>(T p0, T1 p1);
public delegate void MyAction<T, T1, T2>(T p0, T1 p1, T2 p2);

[DisplayName("transfer")]
public static event MyAction<byte[], byte[], BigInteger> Transferred;
[DisplayName("refund")]
public static event MyAction<byte[], BigInteger> Refund;
```

big thanks to `jianying li(a coder)` on discord. kindly help me debug this.

It's about `System.Action` that is defined in `mscorlib.dll` on windows but in `mono` it's maybe in somewhere else. making `neon.dll` unable to find it.

**Comment by mwherman2000** [comment]
I've also documented the problem (and solution) here ...with some step by step instructions: https://github.com/mwherman2000/neo-windocs/blob/master/windocs/neo-problems/ICO-Template-Problems.md

**Comment by NeoParticle** [comment]
Hi, Copying mscorlib.dll to debug or release folder is not a straight forward solution. 
Add the mscorlib.dll into the solution and in property of the added file set "Copy to Output Directory" as "Copy always"

**Comment by niastakevin** [comment]
1. open example-csharp-master
2. open example.sln with visual studio
3. re-install Neo.SmartContract.Framework (remove Neo.SmartContract.Framework first)
(then right clik on reference, choose Manage NuGet Packages, uninstall Neo.SmartContract.Framework, install again)
4. Add Reference--> Assemblies --> choose mscorlib.dll then OK)
5. Build the ICO Templates C#

worked with me.

**Comment by Chubby-Chocobo** [comment]
Some above workaround helps.
