### ISSUE TITLE
ICO_Template has overfunding bug

### ISSUE THREAD

**Issue by wy** [neo-project/examples-csharp#6]
It is possible to overfund the ICO with the current code.

The current MintTokens() method checks using CurrentSwapRate() whether or not Total_Supply >= Total_Amount however it doesn't check if receiving this incoming NEO asset will take the Total_Supply over the amount raised.

This has the unlikely but possible situation that the last person to input assets could have sent a huge amount of NEO which means they will overfund the ICO and receive loads of tokens.

I have a fix for this so raising this as an issue which I've been working on.

**Comment by luodanwg** [comment]
you are right, actually we are also testing on this ICO template , and maybe the next day will pull a update on it.

**Comment by cassidykeyser** [comment]
wy, how's that fix you were working on coming along?

**Comment by wy** [comment]
I believe that red pulse fixed it so will wait until their release their
implementation
